class PurchaseOrder < ActiveRecord::Base

  belongs_to :customer
  belongs_to :approved_by, class_name: 'User', foreign_key: 'user_id'
  belongs_to :asset
  belongs_to :department
  belongs_to :company
  belongs_to :requisition
  has_many :requisition_particulars
  belongs_to :requested_by, class_name: 'User', foreign_key: 'requisition_requested_by_id'

  # paperclip dropbox below
  # config/dropbox.yml, linked to application.yml < generated by figaro

  before_save :rename_upload_image

  has_attached_file :po_image1, :default_url => "default.jpg",
                    storage: :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => 'purchase_order/:filename'
  validates_attachment_content_type :po_image1, :content_type => /\Aimage\/.*\Z/

  has_attached_file :po_image2, :default_url => "default.jpg",
                    storage: :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => 'purchase_order/:filename'
  validates_attachment_content_type :po_image2, :content_type => /\Aimage\/.*\Z/

  has_attached_file :po_image3, :default_url => "default.jpg",
                    storage: :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => 'purchase_order/:filename'
  validates_attachment_content_type :po_image3, :content_type => /\Aimage\/.*\Z/

  protected

  def rename_upload_image
    if self.po_image1.dirty?
      Time.zone = 'Singapore'
      extension = File.extname(po_image1_file_name).downcase
      self.po_image1.instance_write :file_name, "#{Time.zone.now.strftime("%m-%d-%Y")}/purchase_order_A_#{Time.zone.now.strftime("%m%d%Y-%H%M%S")}#{extension}"
    end

    if self.po_image2.dirty?
      Time.zone = 'Singapore'
      extension = File.extname(po_image2_file_name).downcase
      self.po_image2.instance_write :file_name, "#{Time.zone.now.strftime("%m-%d-%Y")}/purchase_order_B_#{Time.zone.now.strftime("%m%d%Y-%H%M%S")}#{extension}"
    end

    if self.po_image3.dirty?
      Time.zone = 'Singapore'
      extension = File.extname(po_image3_file_name).downcase
      self.po_image3.instance_write :file_name, "#{Time.zone.now.strftime("%m-%d-%Y")}/purchase_order_C_#{Time.zone.now.strftime("%m%d%Y-%H%M%S")}#{extension}"
    end
  end

end
